/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface TemplatePortal {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLTemplatePortalElement extends Components.TemplatePortal, HTMLStencilElement {
    }
    var HTMLTemplatePortalElement: {
        prototype: HTMLTemplatePortalElement;
        new (): HTMLTemplatePortalElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "template-portal": HTMLTemplatePortalElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface TemplatePortal {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "template-portal": TemplatePortal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "template-portal": LocalJSX.TemplatePortal & JSXBase.HTMLAttributes<HTMLTemplatePortalElement>;
        }
    }
}
